# Generated by Django 2.1 on 2018-11-16 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evalapp', '0003_appliedeval_appliedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='metaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.DecimalField(decimal_places=2, max_digits=2)),
                ('aboutReport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportsAboutReports', to='evalapp.appliedEval')),
                ('forUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metaReporters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
