# Generated by Django 2.1 on 2018-11-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalapp', '0004_metareport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metareport',
            name='aboutReport',
        ),
        migrations.RemoveField(
            model_name='metareport',
            name='forUser',
        ),
        migrations.DeleteModel(
            name='metaReport',
        ),
    ]
